package dai.luis.models;

// Generated 24-oct-2017 8:06:34 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Almacenes generated by hbm2java
 */
@Entity
@Table(name = "almacenes", catalog = "pruebas")
public class Almacen implements java.io.Serializable {
	private static final long serialVersionUID = 4944615340683546366L;
	
	public Almacen() {
	}
	
	public Almacen(String nombreAlmacen, String telefono,
			Set<Producto> productos) {
		this.nombreAlmacen = nombreAlmacen;
		this.telefono = telefono;
		this.productos = productos;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_almacen", unique = true, nullable = false)
	private Long idAlmacen;
	
	@Column(name = "nombre_almacen", length = 100)
	private String nombreAlmacen;
	
	@Column(name = "telefono", length = 20)
	private String telefono;
	
	/*No es activo = 0, Es Activo != 0*/
	@Column(name = "esactivo", nullable = false)
	private Integer esActivo;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "almacen",cascade = CascadeType.ALL)
	private Set<Producto> productos = new HashSet<Producto>(0);
	
	public Long getIdAlmacen() {
		return this.idAlmacen;
	}

	public void setIdAlmacen(Long idAlmacen) {
		this.idAlmacen = idAlmacen;
	}

	public String getNombreAlmacen() {
		return this.nombreAlmacen;
	}

	public void setNombreAlmacen(String nombreAlmacen) {
		this.nombreAlmacen = nombreAlmacen;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public Integer getEsActivo() {
		return esActivo;
	}

	public void setEsActivo(Integer esActivo) {
		this.esActivo = esActivo;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Set<Producto> getProductos() {
		return productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
