package dai.luis.models;

// Generated 24-oct-2017 8:06:34 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name = "productos", catalog = "pruebas")
public class Producto implements java.io.Serializable {
	private static final long serialVersionUID = 745887119326850886L;

	public Producto() {
	}
	
	public Producto(Almacen almacenes, float pvp) {
		this.almacen = almacenes;
		this.pvp = pvp;
	}
	
	public Producto(Almacen almacenes, String nombreProducto, float pvp) {
		this.almacen = almacenes;
		this.nombreProducto = nombreProducto;
		this.pvp = pvp;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_producto", unique = true, nullable = false)
	private Long idProducto;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_almacen", nullable = false)
	private Almacen almacen;
	
	@Column(name = "nombre_producto", length = 100)
	private String nombreProducto;
	
	@Column(name = "pvp", nullable = false, precision = 12, scale = 0)
	private Float pvp;

	public Long getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Long idProducto) {
		this.idProducto = idProducto;
	}

	public String getNombreProducto() {
		return this.nombreProducto;
	}

	public void setNombreProducto(String nombreProducto) {
		this.nombreProducto = nombreProducto;
	}

	public Float getPvp() {
		return pvp;
	}

	public void setPvp(Float pvp) {
		this.pvp = pvp;
	}

	public Almacen getAlmacen() {
		return almacen;
	}

	public void setAlmacen(Almacen almacen) {
		this.almacen = almacen;
	}
	
}
